-- Drop existing tables if they exist
DROP TABLE IF EXISTS DAY CASCADE;
DROP TABLE IF EXISTS SPLIT CASCADE;
DROP TABLE IF EXISTS SET CASCADE;
DROP TABLE IF EXISTS EXERCISE_HISTORY CASCADE;
DROP TABLE IF EXISTS WORKOUT_EXERCISE CASCADE;
DROP TABLE IF EXISTS WORKOUT CASCADE;
DROP TABLE IF EXISTS EXERCISE CASCADE;
DROP TABLE IF EXISTS APP_USER CASCADE;

-- App User table
CREATE TABLE APP_USER (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Exercise table (exercise templates/definitions)
CREATE TABLE EXERCISE (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    EXE_NAME VARCHAR(255) NOT NULL,
    EXE_USER_ID UUID NOT NULL REFERENCES APP_USER(ID) ON DELETE CASCADE,
    EXE_DATE TIMESTAMP NOT NULL,
    EXE_MAX_REPS INTEGER,
    EXE_MAX_WEIGHT DECIMAL(10, 2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Workout table (workout sessions/templates)
CREATE TABLE WORKOUT (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    WOR_NAME VARCHAR(255) NOT NULL,
    WOR_USER_ID UUID NOT NULL REFERENCES APP_USER(ID) ON DELETE CASCADE,
    WOR_COMPLETED_COUNT INTEGER DEFAULT 0,
    WOR_ESTIMATE_TIME INTEGER,
    WOR_LAST_DONE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Workout Exercise table (exercises within a workout)
CREATE TABLE WORKOUT_EXERCISE (
    WOE_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    WORKOUT_ID UUID NOT NULL REFERENCES WORKOUT(ID) ON DELETE CASCADE,
    EXERCISE_ID UUID NOT NULL REFERENCES EXERCISE(ID) ON DELETE CASCADE,
    ORDINAL INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(WORKOUT_ID, ORDINAL)
);

-- Exercise History table (records of completed exercises)
CREATE TABLE EXERCISE_HISTORY (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    EXERCISE_ID UUID NOT NULL REFERENCES EXERCISE(ID) ON DELETE CASCADE,
    EXH_DATE TIMESTAMP NOT NULL,
    EXH_COMMENT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Set table (individual sets within an exercise history)
CREATE TABLE SET (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    EXERCISE_HISTORY_ID UUID NOT NULL REFERENCES EXERCISE_HISTORY(ID) ON DELETE CASCADE,
    SET_WEIGHT DECIMAL(10, 2) NOT NULL,
    SET_REPS INTEGER NOT NULL,
    SET_ORDER INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Split table (weekly workout splits)
CREATE TABLE SPLIT (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID UUID NOT NULL REFERENCES APP_USER(ID) ON DELETE CASCADE,
    SPL_REF_WEEK INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Day table (individual days within a split week)
CREATE TABLE DAY (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    SPLIT_ID UUID NOT NULL REFERENCES SPLIT(ID) ON DELETE CASCADE,
    WORKOUT_ID UUID REFERENCES WORKOUT(ID) ON DELETE SET NULL,
    DAY_NAME VARCHAR(20) NOT NULL,
    COMPLETED BOOLEAN DEFAULT FALSE,
    WEEK_DAY_INDEX INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(SPLIT_ID, WEEK_DAY_INDEX)
);

-- Create indexes for common queries
CREATE INDEX IDX_EXERCISE_USER_ID ON EXERCISE(EXE_USER_ID);
CREATE INDEX IDX_WORKOUT_USER_ID ON WORKOUT(WOR_USER_ID);
CREATE INDEX IDX_WORKOUT_EXERCISE_WORKOUT_ID ON WORKOUT_EXERCISE(WORKOUT_ID);
CREATE INDEX IDX_WORKOUT_EXERCISE_EXERCISE_ID ON WORKOUT_EXERCISE(EXERCISE_ID);
CREATE INDEX IDX_EXERCISE_HISTORY_EXERCISE_ID ON EXERCISE_HISTORY(EXERCISE_ID);
CREATE INDEX IDX_EXERCISE_HISTORY_DATE ON EXERCISE_HISTORY(EXH_DATE);
CREATE INDEX IDX_SET_EXERCISE_HISTORY_ID ON SET(EXERCISE_HISTORY_ID);
CREATE INDEX IDX_SPLIT_USER_ID ON SPLIT(USER_ID);
CREATE INDEX IDX_DAY_SPLIT_ID ON DAY(SPLIT_ID);

-- Enable Row Level Security (RLS) - Optional but recommended
-- ALTER TABLE EXERCISE ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE WORKOUT ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE WORKOUT_EXERCISE ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE EXERCISE_HISTORY ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE SET ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE SPLIT ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE DAY ENABLE ROW LEVEL SECURITY;

-- Example RLS policies (uncomment and customize as needed)
-- CREATE POLICY "Users can view their own exercises" ON EXERCISE
--     FOR SELECT USING (auth.uid()::uuid = EXE_USER_ID);

-- CREATE POLICY "Users can view their own workouts" ON WORKOUT
--     FOR SELECT USING (auth.uid()::uuid = WOR_USER_ID);
